### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by SirDeveloperOrg** [QRCS-CORP/QSC#1]
Hi, how can I contact you?

**Comment by Steppenwolfe65** [comment]
Hey, here for starters.. what are you looking for?

**Comment by SirDeveloperOrg** [comment]
Thanks for your response, I wanted to ask is CEX-NET still secure?
I using ChaCha20 and Ring-LWE.

**Comment by Steppenwolfe65** [comment]
The .NET version was made years before the NIST Post Quantum competition was held, there are new versions of those ciphers, ones that have been vetted by the community, so in short, the answer is 'no', there are better alternatives now.
This was announced on the GitHub page of the CEX .NET library, it is clearly stated as being 'for historical purposes only', because it is *retired*.
The versions in this library are current, the implementations from the 3rd round of NIST PQ.
ChaCha hasn't changed, but there are versions of it using intrinsics in this library which are much faster, and superior authenticated symmetric stream-ciphers like RCS and CSX.

**Comment by SirDeveloperOrg** [comment]
Can I contact you in private? if you accept requests I can pay you.

**Comment by Steppenwolfe65** [comment]
No thank you, but good luck with your project.
